title: Monad Improvement Proposals
description: Monad Improvement Proposals (MIPs)
url: "https://mips.monad.xyz"
baseurl: 
lang: en
timezone: UTC

lsi: false
safe: true
incremental: false
theme: minima
markdown: kramdown
highlighter: none
permalink: /:path

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: null

gist:
  noscript: false

defaults:
  -
    scope:
      path: "MIPs"
    values:
      layout: "proposal"
  -
    scope:
      path: "MRCs"
    values:
      layout: "proposal"

exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

include:
  - LICENSE.md

sass:
  style: compressed
  sourcemap: never
  quiet_deps: true
  silence_deprecations:
    - import
